// app.logic.js — appended after the HebCal IIFE bundle in app.js
/* global HebCal */

var SunCalc = require("suncalc");
var Layout = require("Layout");
var Locale = require("locale");

var loc = require("Storage").readJSON("mylocation.json", 1) || { lat: 31.78, lon: 35.23 };
var appSettings = require("Storage").readJSON("hebrew_calendar.json", 1) || { inIsrael: false };

var dayInMS = 86400000;
var hebrewCalendar = [];

// Sunset on a given Date at the stored location.
function sunsetOn(date) {
  return SunCalc.getTimes(date, loc.lat, loc.lon).sunset;
}

// Compute events for the next 7 days (plus yesterday to catch active events).
function computeEvents() {
  var il = !!appSettings.inIsrael;
  var today = new Date();
  today.setHours(0, 0, 0, 0);
  // Start from yesterday to include events whose startEvent is yesterday's sunset.
  var rangeStart = new Date(today.getTime() - dayInMS);
  var rangeEnd   = new Date(today.getTime() + 8 * dayInMS);

  var rawEvents = HebCal.HebrewCalendar.calendar({
    il: il,
    start: rangeStart,
    end: rangeEnd,
    addHebrewDates: true,
    noModern: true,
  });

  var events = [];
  var F = HebCal.flags;

  rawEvents.forEach(function(ev) {
    var gregDate = ev.date.greg();
    // noon on greg date (avoids DST edge cases)
    var noonDate = new Date(gregDate.getFullYear(), gregDate.getMonth(), gregDate.getDate(), 12);
    var prevNoon = new Date(noonDate.getTime() - dayInMS);
    var sunset    = sunsetOn(noonDate).getTime();
    var prevSunset = sunsetOn(prevNoon).getTime();
    var havdalah  = sunset + 42 * 60000;
    var dayStart  = new Date(gregDate.getFullYear(), gregDate.getMonth(), gregDate.getDate()).getTime();

    var mask = ev.mask;

    if (mask & F.HEBREW_DATE) {
      // Show Hebrew date label for the civil day.
      events.push({ desc: ev.getDesc(), startEvent: dayStart, endEvent: dayStart + dayInMS });
      return;
    }

    if (mask & F.LIGHT_CANDLES) {
      // Erev holiday — candle lighting 18 min before sunset.
      var cl = sunset - 18 * 60000;
      events.push({ desc: "Candle lighting", startEvent: cl, endEvent: cl + 900000 });
      return; // the "Erev X" label itself isn't needed; candle lighting covers it
    }

    if (mask & F.LIGHT_CANDLES_TZEIS) {
      // First of a two-day Yom Tov in diaspora — holiday runs prevSunset→sunset,
      // then candle lighting at nightfall for day 2.
      events.push({ desc: ev.getDesc(), startEvent: prevSunset, endEvent: sunset });
      var tzeis = sunset + 42 * 60000;
      events.push({ desc: "Candle lighting", startEvent: tzeis, endEvent: tzeis + 900000 });
      return;
    }

    if (mask & F.YOM_TOV_ENDS) {
      // Last day of Yom Tov — ends at havdalah.
      events.push({ desc: ev.getDesc(), startEvent: prevSunset, endEvent: havdalah });
      return;
    }

    if (mask & F.CHAG) {
      // Middle/sole Yom Tov day — runs prevSunset to sunset.
      events.push({ desc: ev.getDesc(), startEvent: prevSunset, endEvent: sunset });
      return;
    }

    if (mask & F.ROSH_CHODESH) {
      events.push({ desc: ev.getDesc(), startEvent: dayStart, endEvent: dayStart + dayInMS });
      return;
    }

    // Minor holidays, fasts, special Shabbatot — show for the civil day.
    if (mask & (F.MINOR_FAST | F.MAJOR_FAST | F.MINOR_HOLIDAY | F.SPECIAL_SHABBAT | F.CHANUKAH_CANDLES)) {
      events.push({ desc: ev.getDesc(), startEvent: dayStart, endEvent: dayStart + dayInMS });
    }
  });

  // Add Shabbat events (not generated by HebrewCalendar without candlelighting:true).
  for (var i = -1; i <= 8; i++) {
    var d = new Date(today.getTime() + i * dayInMS);
    var dow = d.getDay();
    if (dow === 5) {
      // Friday: candle lighting 18 min before sunset.
      var fSunset = sunsetOn(new Date(d.getFullYear(), d.getMonth(), d.getDate(), 12)).getTime();
      var fCL = fSunset - 18 * 60000;
      events.push({ desc: "Candle lighting", startEvent: fCL, endEvent: fCL + 900000 });
    }
    if (dow === 6) {
      // Saturday: Shabbat runs from Friday sunset to Saturday nightfall.
      var sSunday = new Date(d.getFullYear(), d.getMonth(), d.getDate(), 12);
      var sFriday = new Date(sSunday.getTime() - dayInMS);
      var shabbatStart = sunsetOn(sFriday).getTime();
      var shabbatEnd   = sunsetOn(sSunday).getTime() + 42 * 60000;
      events.push({ desc: "Shabbat", startEvent: shabbatStart, endEvent: shabbatEnd });
    }
  }

  var now = Date.now();
  return events
    .filter(function(e) { return e.endEvent > now - dayInMS; })
    .sort(function(a, b) { return a.startEvent - b.startEvent; });
}

function getCurrentEvents() {
  var now = Date.now();
  var current = hebrewCalendar.filter(function(x) {
    return x.startEvent <= now && x.endEvent >= now;
  });
  return current.map(function(event, i) {
    return {
      type: "txt",
      font: "12x20",
      id: "currentEvents" + i,
      label: event.desc,
      pad: 2,
      bgCol: g.theme.bg,
    };
  });
}

function getUpcomingEvents() {
  var now = Date.now();
  var futureEvents = hebrewCalendar.filter(function(x) {
    return x.startEvent >= now && x.startEvent <= now + dayInMS;
  });
  return futureEvents.slice(0, 2).map(function(event, i) {
    return {
      startEvent: event.startEvent,
      type: "txt",
      font: "6x8",
      id: "upcomingEvents" + i,
      label: event.desc + " at " + Locale.time(new Date(event.startEvent), 1),
      pad: 2,
      bgCol: g.theme.bg,
    };
  }).sort(function(a, b) { return a.startEvent - b.startEvent; });
}

function dateTime() {
  return (
    Locale.dow(new Date(), 1) +
    " " +
    Locale.date(new Date(), 1) +
    " " +
    Locale.time(new Date(), 1)
  );
}

function makeLayout() {
  return new Layout(
    {
      type: "v",
      c: [
        {
          type: "txt",
          font: "6x8",
          id: "title",
          label: "-- Hebrew Calendar Events --",
          pad: 2,
          bgCol: g.theme.bg2,
        },
        {
          type: "txt",
          font: "6x8",
          id: "currently",
          label: "Currently",
          pad: 2,
          bgCol: g.theme.bgH,
        },
      ]
        .concat(getCurrentEvents())
        .concat([
          {
            type: "txt",
            font: "6x8",
            label: "Upcoming",
            id: "upcoming",
            pad: 2,
            bgCol: g.theme.bgH,
          },
        ])
        .concat(getUpcomingEvents())
        .concat([
          {
            type: "txt",
            font: "Vector14",
            id: "time",
            label: dateTime(),
            pad: 2,
            bgCol: undefined,
          },
        ]),
    },
    { lazy: true }
  );
}

var layout = makeLayout();
var drawTimeout;

function draw() {
  layout.time.label = dateTime();
  layout.render();
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  }, 60000 - (Date.now() % 60000));
}

g.clear();
Bangle.setUI("clock");
Bangle.loadWidgets();
Bangle.drawWidgets();

hebrewCalendar = computeEvents();
layout = makeLayout();
draw();

function updateCalendar() {
  hebrewCalendar = computeEvents();
  layout.clear();
  layout = makeLayout();
  layout.forgetLazyState();
  layout.render();

  var now = Date.now();
  var nextChange = dayInMS;

  hebrewCalendar.forEach(function(ev) {
    if (ev.startEvent > now) nextChange = Math.min(nextChange, ev.startEvent - now + 5000);
    if (ev.endEvent > now)   nextChange = Math.min(nextChange, ev.endEvent - now + 5000);
  });

  // Also recompute at midnight to roll the 7-day window.
  var msTillMidnight = dayInMS - (now % dayInMS);
  nextChange = Math.min(nextChange, msTillMidnight + 5000);

  setTimeout(updateCalendar, nextChange);
}

updateCalendar();
