// Stub for @hebcal/core YomKippurKatanEvent.js.
// YomKippurKatan is generated by holidays.js (not just when options.yomKippurKatan
// is set). The constructor must store the date so i(ev).date.toString() works.
export function YomKippurKatanEvent(date) { this.date = date; }
YomKippurKatanEvent.prototype.getDesc = function() { return ''; };
YomKippurKatanEvent.prototype.mask = 0;
YomKippurKatanEvent.prototype.getFlags = function() { return 0; };
YomKippurKatanEvent.prototype.observedIn = function() { return true; };
